-- Create movies table
CREATE TABLE movies (
    movie_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    release_date DATE,
    director_id INT,
    FOREIGN KEY (director_id) REFERENCES directors(director_id) ON DELETE CASCADE
);

-- Create movie_genres table
CREATE TABLE movie_genres (
    movie_id INT,
    genre_id INT,
    PRIMARY KEY (movie_id, genre_id),
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres(genre_id) ON DELETE CASCADE
);

-- Insert movies
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (1, 'The Shawshank Redemption', '1994-10-14', 1); 
INSERT INTO movie_genres (movie_id, genre_id) VALUES (1, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (2, 'The Godfather', '1972-03-24', 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (2, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (2, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (3, 'The Dark Knight', '2008-07-18', 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (3, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (3, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (3, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (4, 'The Godfather: Part II', '1974-12-18', 2);   
INSERT INTO movie_genres (movie_id, genre_id) VALUES (4, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (4, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (5, '12 Angry Men', '1957-04-10', 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (5, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (5, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (6, 'Schindler''s List', '1994-02-04', 5);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (6, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (6, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (6, 5);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (7, 'The Lord of the Rings: The Return of the King', '2003-12-17', 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (7, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (7, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (7, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (8, 'Pulp Fiction', '1994-10-14', 7);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (8, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (8, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (9, 'The Lord of the Rings: The Fellowship of the Ring', '2001-12-19', 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (9, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (9, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (9, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (10, 'The Good, the Bad and the Ugly', '1967-12-29', 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (10, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (10, 7);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (11, 'Forrest Gump', '1994-07-06', 9);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (11, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (11, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (12, 'Fight Club', '1999-10-15', 10);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (12, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (13, 'Inception', '2010-07-16', 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (13, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (13, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (13, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (14, 'The Lord of the Rings: The Two Towers', '2002-12-18', 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (14, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (14, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (14, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (15, 'Star Wars: Episode V - The Empire Strikes Back', '1980-06-20', 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (15, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (15, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (15, 10);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (16, 'The Matrix', '1999-03-31', 12);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (16, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (16, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (17, 'Goodfellas', '1990-09-21', 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (17, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (17, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (17, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (18, 'One Flew Over the Cuckoo''s Nest', '1975-11-19', 14);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (18, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (19, 'Se7en', '1995-09-22', 10);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (19, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (19, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (19, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (20, 'Seven Samurai', '1956-11-19', 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (20, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (20, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (21, 'It''s a Wonderful Life', '1947-01-07', 16); 
INSERT INTO movie_genres (movie_id, genre_id) VALUES (21, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (21, 12);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (21, 10);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (22, 'The Silence of the Lambs', '1991-02-14', 17);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (22, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (22, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (22, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (23, 'Saving Private Ryan', '1998-07-24', 5);     
INSERT INTO movie_genres (movie_id, genre_id) VALUES (23, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (23, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (24, 'City of God', '2004-02-13', 18);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (24, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (24, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (25, 'Life Is Beautiful', '1997-12-20', 19);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (25, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (25, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (25, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (26, 'The Green Mile', '1999-12-10', 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (26, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (26, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (26, 10);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (27, 'Star Wars', '1977-05-25', 20);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (27, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (27, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (27, 10);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (28, 'Interstellar', '2014-11-07', 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (28, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (28, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (28, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (29, 'Terminator 2: Judgment Day', '1991-07-03', 21);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (29, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (29, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (30, 'Back to the Future', '1985-07-03', 9);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (30, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (30, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (30, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (31, 'Spirited Away', '2003-03-28', 22);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (31, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (31, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (31, 12);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (32, 'Psycho', '1960-09-08', 23);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (32, 17);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (32, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (32, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (33, 'The Pianist', '2003-03-28', 24);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (33, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (33, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (33, 18);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (34, 'LÃ©on: The Professional', '1994-11-18', 25);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (34, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (34, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (34, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (35, 'Parasite', '2019-11-08', 26);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (35, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (35, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (35, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (36, 'The Lion King', '1994-06-24', 27);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (36, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (36, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (36, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (37, 'Gladiator', '2000-05-05', 28);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (37, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (37, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (37, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (38, 'American History X', '1998-11-20', 29);     
INSERT INTO movie_genres (movie_id, genre_id) VALUES (38, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (39, 'The Usual Suspects', '1995-08-16', 30);     
INSERT INTO movie_genres (movie_id, genre_id) VALUES (39, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (39, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (39, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (40, 'The Departed', '2006-10-06', 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (40, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (40, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (40, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (41, 'The Prestige', '2006-10-20', 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (41, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (41, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (41, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (42, 'Casablanca', '1943-01-23', 31);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (42, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (42, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (42, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (43, 'Whiplash', '2014-10-15', 32);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (43, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (43, 18);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (44, 'The Intouchables', '2011-11-02', 33);       
INSERT INTO movie_genres (movie_id, genre_id) VALUES (44, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (44, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (44, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (45, 'Modern Times', '1936-02-25', 34);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (45, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (45, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (45, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (46, 'Once Upon a Time in the West', '1969-07-04', 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (46, 7);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (47, 'Hara-Kiri', '1964-08-04', 35);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (47, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (47, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (47, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (48, 'Grave of the Fireflies', '1989-07-26', 36); 
INSERT INTO movie_genres (movie_id, genre_id) VALUES (48, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (48, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (48, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (49, 'Alien', '1979-06-22', 28);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (49, 17);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (49, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (50, 'Rear Window', '1954-09-01', 23);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (50, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (50, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (51, 'City Lights', '1931-03-07', 34);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (51, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (51, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (51, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (52, 'Memento', '2001-05-25', 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (52, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (52, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (53, 'Cinema Paradiso', '1990-02-23', 37);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (53, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (53, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (54, 'Apocalypse Now', '1979-08-15', 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (54, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (54, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (54, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (55, 'Indiana Jones and the Raiders of the Lost Ark', '1981-06-12', 5);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (55, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (55, 6);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (56, 'Django Unchained', '2012-12-25', 7);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (56, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (56, 7);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (57, 'WALLÂ·E', '2008-06-27', 38);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (57, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (57, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (57, 12);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (58, 'The Lives of Others', '2007-03-30', 39);    
INSERT INTO movie_genres (movie_id, genre_id) VALUES (58, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (58, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (58, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (59, 'Sunset Blvd.', '1950-08-04', 40);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (59, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (59, 19);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (60, 'The Shining', '1980-06-13', 41);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (60, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (60, 17);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (61, 'Paths of Glory', '1957-12-25', 41);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (61, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (61, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (62, 'The Great Dictator', '1941-03-07', 34);     
INSERT INTO movie_genres (movie_id, genre_id) VALUES (62, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (62, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (62, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (63, 'Avengers: Infinity War', '2018-04-27', 42); 
INSERT INTO movie_genres (movie_id, genre_id) VALUES (63, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (63, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (63, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (64, 'Witness for the Prosecution', '1958-02-06', 40);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (64, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (64, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (64, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (65, 'Aliens', '1986-07-18', 21);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (65, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (65, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (65, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (66, 'American Beauty', '1999-10-01', 43);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (66, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (67, 'The Dark Knight Rises', '2012-07-20', 3);   
INSERT INTO movie_genres (movie_id, genre_id) VALUES (67, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (67, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (67, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (68, 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', '1964-01-29', 41);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (68, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (68, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (69, 'Spider-Man: Into the Spider-Verse', '2018-12-14', 44);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (69, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (69, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (69, 6);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (70, 'Joker', '2019-10-04', 45);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (70, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (70, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (70, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (71, 'Old Boy', '2003-11-21', 46);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (71, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (71, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (71, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (72, 'Braveheart', '1995-05-24', 47);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (72, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (72, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (72, 5);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (73, 'Toy Story', '1995-11-22', 48);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (73, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (73, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (73, 15);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (74, 'Amadeus', '1984-09-19', 14);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (74, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (74, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (74, 18);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (75, 'Coco', '2017-11-22', 49);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (75, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (75, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (75, 15);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (76, 'Spider-Man: No Way Home', '2021-12-17', 50);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (76, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (76, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (76, 10);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (77, 'Inglourious Basterds', '2009-08-21', 7);    
INSERT INTO movie_genres (movie_id, genre_id) VALUES (77, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (77, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (77, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (78, 'The Boat', '1982-02-10', 51);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (78, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (78, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (79, 'Avengers: Endgame', '2019-04-26', 42);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (79, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (79, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (79, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (80, 'Princess Mononoke', '1997-12-19', 22);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (80, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (80, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (80, 6);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (81, 'Once Upon a Time in America', '1984-06-01', 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (81, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (81, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (82, 'Good Will Hunting', '1998-01-09', 52);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (82, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (82, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (83, 'Toy Story 3', '2010-06-18', 53);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (83, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (83, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (83, 15);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (84, 'Requiem for a Dream', '2000-12-15', 54);    
INSERT INTO movie_genres (movie_id, genre_id) VALUES (84, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (85, '3 Idiots', '2009-12-25', 55);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (85, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (85, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (86, 'Your Name.', '2017-04-07', 56);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (86, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (86, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (86, 10);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (87, 'Singin'' in the Rain', '1952-04-11', 57);   
INSERT INTO movie_genres (movie_id, genre_id) VALUES (87, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (87, 20);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (87, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (88, 'Star Wars: Episode VI - Return of the Jedi', '1983-05-25', 58);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (88, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (88, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (88, 10);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (89, 'Reservoir Dogs', '1992-09-02', 7);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (89, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (89, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (89, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (90, 'Eternal Sunshine of the Spotless Mind', '2004-03-19', 59);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (90, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (90, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (90, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (91, '2001: A Space Odyssey', '1970-06-24', 41);  
INSERT INTO movie_genres (movie_id, genre_id) VALUES (91, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (91, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (92, 'High and Low', '1963-11-26', 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (92, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (92, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (92, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (93, 'Citizen Kane', '1941-09-05', 60);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (93, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (93, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (94, 'Lawrence of Arabia', '1962-12-11', 61);     
INSERT INTO movie_genres (movie_id, genre_id) VALUES (94, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (94, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (94, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (95, 'Capernaum', '2018-09-20', 62);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (95, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (96, 'M', '1931-08-31', 63);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (96, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (96, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (96, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (97, 'North by Northwest', '1959-12-18', 23);     
INSERT INTO movie_genres (movie_id, genre_id) VALUES (97, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (97, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (97, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (98, 'The Hunt', '2013-01-10', 64);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (98, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (99, 'Vertigo', '1958-05-22', 23);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (99, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (99, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (99, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (100, 'AmÃ©lie', '2002-02-08', 65);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (100, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (100, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (101, 'A Clockwork Orange', '1972-02-02', 41);    
INSERT INTO movie_genres (movie_id, genre_id) VALUES (101, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (101, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (102, 'Full Metal Jacket', '1987-07-10', 41);     
INSERT INTO movie_genres (movie_id, genre_id) VALUES (102, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (102, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (103, 'Scarface', '1983-12-09', 66);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (103, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (103, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (104, 'Come and See', '1985-09-03', 67);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (104, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (104, 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (104, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (105, 'Double Indemnity', '1944-07-06', 40);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (105, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (105, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (105, 19);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (106, 'The Apartment', '1960-06-29', 40);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (106, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (106, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (106, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (107, 'Taxi Driver', '1976-02-09', 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (107, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (107, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (108, 'To Kill a Mockingbird', '1963-03-16', 68); 
INSERT INTO movie_genres (movie_id, genre_id) VALUES (108, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (108, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (109, 'The Sting', '1973-12-25', 69);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (109, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (109, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (109, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (110, 'Up', '2009-05-29', 70);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (110, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (110, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (110, 15);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (111, 'L.A. Confidential', '1997-09-19', 71);     
INSERT INTO movie_genres (movie_id, genre_id) VALUES (111, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (111, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (111, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (112, 'Hamilton', '2020-07-03', 72);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (112, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (112, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (112, 5);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (113, 'Heat', '1995-12-15', 73);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (113, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (113, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (113, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (114, 'Ikiru', '1956-03-25', 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (114, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (115, 'Snatch', '2001-01-19', 74);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (115, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (115, 2);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (116, 'Die Hard', '1988-07-20', 75);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (116, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (116, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (117, 'Indiana Jones and the Last Crusade', '1989-05-24', 5);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (117, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (117, 6);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (118, 'A Separation', '2011-03-16', 76);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (118, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (119, 'Metropolis', '1927-03-13', 63);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (119, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (119, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (120, 'Bicycle Thieves', '1949-12-13', 77);       
INSERT INTO movie_genres (movie_id, genre_id) VALUES (120, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (121, 'Incendies', '2011-01-12', 78);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (121, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (121, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (121, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (122, '1917', '2020-01-10', 43);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (122, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (122, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (122, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (123, 'Like Stars on Earth', '2007-12-21', 79);   
INSERT INTO movie_genres (movie_id, genre_id) VALUES (123, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (123, 12);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (124, 'Batman Begins', '2005-06-15', 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (124, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (124, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (124, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (125, 'For a Few Dollars More', '1967-05-10', 8); 
INSERT INTO movie_genres (movie_id, genre_id) VALUES (125, 7);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (126, 'Dangal', '2016-12-21', 80);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (126, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (126, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (126, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (127, 'Downfall', '2005-04-08', 81);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (127, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (127, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (127, 5);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (128, 'The Kid', '1921-02-06', 34);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (128, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (128, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (128, 12);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (129, 'Some Like It Hot', '1959-03-19', 40);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (129, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (129, 18);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (129, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (130, 'The Batman', '2022-03-04', 82);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (130, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (130, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (130, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (131, 'The Father', '2021-02-26', 83);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (131, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (131, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (132, 'All About Eve', '1950-10-27', 84);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (132, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (133, 'The Wolf of Wall Street', '2013-12-25', 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (133, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (133, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (133, 2);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (134, 'Green Book', '2018-11-16', 85);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (134, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (134, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (134, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (135, 'Unforgiven', '1992-08-07', 86);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (135, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (135, 7);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (136, 'Casino', '1995-11-22', 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (136, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (136, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (137, 'Judgment at Nuremberg', '1961-12-18', 87); 
INSERT INTO movie_genres (movie_id, genre_id) VALUES (137, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (137, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (138, 'Pan''s Labyrinth', '2007-01-19', 88);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (138, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (138, 10);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (138, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (139, 'Ran', '1985-06-01', 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (139, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (139, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (139, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (140, 'A Beautiful Mind', '2002-01-04', 89);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (140, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (140, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (141, 'The Sixth Sense', '1999-08-06', 90);       
INSERT INTO movie_genres (movie_id, genre_id) VALUES (141, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (141, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (141, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (142, 'Monty Python and the Holy Grail', '1975-05-25', 91);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (142, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (142, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (142, 10);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (143, 'There Will Be Blood', '2008-01-25', 92);   
INSERT INTO movie_genres (movie_id, genre_id) VALUES (143, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (144, 'The Truman Show', '1998-06-05', 93);       
INSERT INTO movie_genres (movie_id, genre_id) VALUES (144, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (144, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (145, 'Yojimbo', '1961-09-13', 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (145, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (145, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (145, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (146, 'The Treasure of the Sierra Madre', '1948-01-24', 94);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (146, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (146, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (146, 7);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (147, 'Shutter Island', '2010-02-19', 13);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (147, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (147, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (148, 'The Great Escape', '1963-07-04', 95);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (148, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (148, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (148, 5);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (149, 'Rashomon', '1951-12-26', 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (149, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (149, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (149, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (150, 'Jurassic Park', '1993-06-11', 5);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (150, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (150, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (150, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (151, 'Kill Bill: Vol. 1', '2003-10-10', 7);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (151, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (151, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (151, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (152, 'No Country for Old Men', '2007-11-21', 96);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (152, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (152, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (152, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (153, 'Finding Nemo', '2003-05-30', 97);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (153, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (153, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (153, 15);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (154, 'Raging Bull', '1980-12-19', 13);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (154, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (154, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (154, 21);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (155, 'V for Vendetta', '2006-03-17', 98);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (155, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (155, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (155, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (156, 'The Elephant Man', '1980-10-10', 99);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (156, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (156, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (157, 'Gone with the Wind', '1940-01-17', 100);   
INSERT INTO movie_genres (movie_id, genre_id) VALUES (157, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (157, 5);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (157, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (158, 'Chinatown', '1974-06-20', 24);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (158, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (158, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (158, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (159, 'Inside Out', '2015-06-19', 101);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (159, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (159, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (159, 15);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (160, 'Lock, Stock and Two Smoking Barrels', '1998-08-28', 74);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (160, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (160, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (160, 2);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (161, 'The Thing', '1982-06-25', 102);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (161, 17);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (161, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (161, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (162, 'Dial M for Murder', '1954-05-29', 23);     
INSERT INTO movie_genres (movie_id, genre_id) VALUES (162, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (162, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (163, 'The Secret in Their Eyes', '2010-05-21', 103);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (163, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (163, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (163, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (164, 'Howl''s Moving Castle', '2005-06-17', 22); 
INSERT INTO movie_genres (movie_id, genre_id) VALUES (164, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (164, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (164, 12);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (165, 'The Bridge on the River Kwai', '1957-12-14', 61);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (165, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (165, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (165, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (166, 'Trainspotting', '1996-08-09', 104);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (166, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (167, 'Three Billboards Outside Ebbing, Missouri', '2017-12-01', 105);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (167, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (167, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (167, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (168, 'Warrior', '2011-09-09', NULL);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (168, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (168, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (168, 21);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (169, 'Gran Torino', '2009-01-09', 86);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (169, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (170, 'Fargo', '1996-04-05', 107);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (170, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (170, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (171, 'My Neighbor Totoro', '1990-07-13', 22);    
INSERT INTO movie_genres (movie_id, genre_id) VALUES (171, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (171, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (171, 12);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (172, 'Prisoners', '2013-09-20', 78);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (172, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (172, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (172, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (173, 'Million Dollar Baby', '2005-01-28', 86);   
INSERT INTO movie_genres (movie_id, genre_id) VALUES (173, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (173, 21);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (174, 'Blade Runner', '1982-06-25', 28);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (174, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (174, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (174, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (175, 'Catch Me If You Can', '2002-12-25', 5);    
INSERT INTO movie_genres (movie_id, genre_id) VALUES (175, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (175, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (175, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (176, 'The Gold Rush', '1925-07-13', 34);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (176, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (176, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (176, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (177, 'On the Waterfront', '1954-06-22', 108);    
INSERT INTO movie_genres (movie_id, genre_id) VALUES (177, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (177, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (177, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (178, 'Children of Heaven', '1999-01-22', 109);   
INSERT INTO movie_genres (movie_id, genre_id) VALUES (178, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (178, 12);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (178, 21);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (179, 'Harry Potter and the Deathly Hallows: Part 2', '2011-07-15', 110);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (179, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (179, 10);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (179, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (180, 'The Third Man', '1949-09-03', 111);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (180, 19);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (180, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (180, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (181, 'Gone Girl', '2014-10-03', 10);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (181, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (181, 11);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (181, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (182, '12 Years a Slave', '2013-11-08', 112);     
INSERT INTO movie_genres (movie_id, genre_id) VALUES (182, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (182, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (182, 5);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (183, 'Ben-Hur', '1959-11-18', 113);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (183, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (183, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (183, 5);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (184, 'The General', '1927-01-02', 114);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (184, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (184, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (184, 15);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (185, 'The Deer Hunter', '1979-02-23', 115);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (185, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (185, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (186, 'Before Sunrise', '1995-01-27', 116);       
INSERT INTO movie_genres (movie_id, genre_id) VALUES (186, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (186, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (187, 'Wild Strawberries', '1959-06-22', 117);    
INSERT INTO movie_genres (movie_id, genre_id) VALUES (187, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (187, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (188, 'In the Name of the Father', '1994-02-25', 118);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (188, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (188, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (188, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (189, 'The Grand Budapest Hotel', '2014-03-28', 119);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (189, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (189, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (189, 2);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (190, 'Mr. Smith Goes to Washington', '1939-10-19', 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (190, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (190, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (191, 'Room', '2016-01-22', 120);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (191, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (191, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (192, 'Hacksaw Ridge', '2016-11-04', 47);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (192, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (192, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (192, 5);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (193, 'Sherlock Jr.', '1924-05-11', 121);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (193, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (193, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (193, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (194, 'Pather Panchali', '1955-08-26', 122);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (194, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (195, 'How to Train Your Dragon', '2010-03-26', 123);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (195, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (195, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (195, 6);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (196, 'The Wages of Fear', '1955-02-16', 124);    
INSERT INTO movie_genres (movie_id, genre_id) VALUES (196, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (196, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (196, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (197, 'Barry Lyndon', '1975-12-18', 41);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (197, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (197, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (197, 5);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (198, 'Memories of Murder', '2003-05-02', 26);    
INSERT INTO movie_genres (movie_id, genre_id) VALUES (198, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (198, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (198, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (199, 'The Seventh Seal', '1958-10-13', 117);     
INSERT INTO movie_genres (movie_id, genre_id) VALUES (199, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (199, 10);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (199, 5);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (200, 'Klaus', '2019-11-15', 125);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (200, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (200, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (200, 15);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (201, 'Mad Max: Fury Road', '2015-05-15', 126);   
INSERT INTO movie_genres (movie_id, genre_id) VALUES (201, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (201, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (201, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (202, 'The Big Lebowski', '1998-03-06', 107);     
INSERT INTO movie_genres (movie_id, genre_id) VALUES (202, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (202, 2);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (203, 'Wild Tales', '2014-08-21', 127);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (203, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (203, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (203, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (204, 'Monsters, Inc.', '2001-11-02', 128);       
INSERT INTO movie_genres (movie_id, genre_id) VALUES (204, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (204, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (204, 15);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (205, 'Mary and Max', '2010-03-12', 129);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (205, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (205, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (205, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (206, 'Jaws', '1975-06-20', 5);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (206, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (206, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (207, 'The Passion of Joan of Arc', '1928-10-25', 130);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (207, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (207, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (207, 5);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (208, 'Hotel Rwanda', '2005-02-04', 131);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (208, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (208, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (208, 5);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (209, 'Rocky', '1976-12-03', 132);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (209, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (209, 21);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (210, 'Dead Poets Society', '1989-06-09', 93);    
INSERT INTO movie_genres (movie_id, genre_id) VALUES (210, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (210, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (211, 'Tokyo Story', '1972-03-13', 133);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (211, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (212, 'Platoon', '1987-02-06', 134);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (212, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (212, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (213, 'Ford v Ferrari', '2019-11-15', 135);       
INSERT INTO movie_genres (movie_id, genre_id) VALUES (213, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (213, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (213, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (214, 'The Terminator', '1984-10-26', 21);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (214, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (214, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (215, 'Stand by Me', '1986-08-22', 136);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (215, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (215, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (216, 'Rush', '2013-09-27', 89);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (216, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (216, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (216, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (217, 'Into the Wild', '2007-10-19', 137);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (217, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (217, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (217, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (218, 'Logan', '2017-03-03', 135);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (218, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (218, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (218, 9);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (219, 'The Wizard of Oz', '1939-08-25', 138);     
INSERT INTO movie_genres (movie_id, genre_id) VALUES (219, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (219, 12);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (219, 10);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (220, 'Spotlight', '2015-11-20', 139);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (220, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (220, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (220, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (221, 'Network', '1976-11-27', 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (221, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (222, 'Groundhog Day', '1993-02-12', 140);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (222, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (222, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (222, 10);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (223, 'Ratatouille', '2007-06-29', 141);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (223, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (223, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (223, 15);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (224, 'The Exorcist', '1973-12-26', 142);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (224, 17);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (225, 'Hachi: A Dog''s Tale', '2010-03-12', 143); 
INSERT INTO movie_genres (movie_id, genre_id) VALUES (225, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (225, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (225, 12);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (226, 'The Incredibles', '2004-11-05', 144);      
INSERT INTO movie_genres (movie_id, genre_id) VALUES (226, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (226, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (226, 6);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (227, 'Before Sunset', '2004-07-30', 116);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (227, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (227, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (228, 'The Best Years of Our Lives', '1947-05-29', 113);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (228, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (228, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (228, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (229, 'Dersu Uzala', '1977-12-20', 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (229, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (229, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (229, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (230, 'Rebecca', '1940-04-12', 23);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (230, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (230, 19);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (230, 11);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (231, 'My Father and My Son', '2005-11-18', 145); 
INSERT INTO movie_genres (movie_id, genre_id) VALUES (231, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (231, 12);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (232, 'Cool Hand Luke', '1967-11-01', 146);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (232, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (232, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (233, 'The Grapes of Wrath', '1940-03-15', 147);  
INSERT INTO movie_genres (movie_id, genre_id) VALUES (233, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (234, 'The Battle of Algiers', '1967-09-20', 148);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (234, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (234, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (235, 'Pirates of the Caribbean: The Curse of the Black Pearl', '2003-07-09', 149);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (235, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (235, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (235, 10);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (236, 'To Be or Not to Be', '1942-03-06', 150);   
INSERT INTO movie_genres (movie_id, genre_id) VALUES (236, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (236, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (236, 14);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (237, 'Amores perros', '2001-04-13', 151);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (237, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (237, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (238, 'The Sound of Music', '1965-04-01', 152);   
INSERT INTO movie_genres (movie_id, genre_id) VALUES (238, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (238, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (238, 12);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (239, 'Life of Brian', '1979-08-17', 153);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (239, 15);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (240, 'The 400 Blows', '1959-11-16', 154);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (240, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (240, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (241, 'Persona', '1967-03-16', 117);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (241, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (241, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (242, 'It Happened One Night', '1934-02-22', 16); 
INSERT INTO movie_genres (movie_id, genre_id) VALUES (242, 15);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (242, 8);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (243, 'La Haine', '1996-02-23', 155);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (243, 2);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (243, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (244, 'Aladdin', '1992-11-25', 156);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (244, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (244, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (244, 15);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (245, 'Dune', '2021-10-22', 78);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (245, 3);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (245, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (245, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (246, 'Beauty and the Beast', '1991-11-22', 157); 
INSERT INTO movie_genres (movie_id, genre_id) VALUES (246, 16);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (246, 12);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (246, 10);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (247, 'Gandhi', '1983-02-25', 158);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (247, 4);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (247, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (248, 'The Help', '2011-08-10', 159);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (248, 1);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (249, 'The Handmaiden', '2016-06-01', 46);        
INSERT INTO movie_genres (movie_id, genre_id) VALUES (249, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (249, 8);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (249, 13);
INSERT INTO movies (movie_id, name, release_date, director_id) VALUES (250, 'Dances with Wolves', '1990-11-21', 160);   
INSERT INTO movie_genres (movie_id, genre_id) VALUES (250, 6);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (250, 1);
INSERT INTO movie_genres (movie_id, genre_id) VALUES (250, 7);