CREATE TABLE directors (
    director_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL
);

INSERT INTO directors (director_id, name) VALUES (1, 'Frank Darabont');
INSERT INTO directors (director_id, name) VALUES (2, 'Francis Ford Coppola');
INSERT INTO directors (director_id, name) VALUES (3, 'Christopher Nolan');
INSERT INTO directors (director_id, name) VALUES (4, 'Sidney Lumet');
INSERT INTO directors (director_id, name) VALUES (5, 'Steven Spielberg');
INSERT INTO directors (director_id, name) VALUES (6, 'Peter Jackson');
INSERT INTO directors (director_id, name) VALUES (7, 'Quentin Tarantino');
INSERT INTO directors (director_id, name) VALUES (8, 'Sergio Leone');
INSERT INTO directors (director_id, name) VALUES (9, 'Robert Zemeckis');
INSERT INTO directors (director_id, name) VALUES (10, 'David Fincher');
INSERT INTO directors (director_id, name) VALUES (11, 'Irvin Kershner');
INSERT INTO directors (director_id, name) VALUES (12, 'Lana Wachowski, Lilly Wachowski');
INSERT INTO directors (director_id, name) VALUES (13, 'Martin Scorsese');
INSERT INTO directors (director_id, name) VALUES (14, 'Milos Forman');
INSERT INTO directors (director_id, name) VALUES (15, 'Akira Kurosawa');
INSERT INTO directors (director_id, name) VALUES (16, 'Frank Capra');
INSERT INTO directors (director_id, name) VALUES (17, 'Jonathan Demme');
INSERT INTO directors (director_id, name) VALUES (18, 'Fernando Meirelles, KÃ¡tia Lund');
INSERT INTO directors (director_id, name) VALUES (19, 'Roberto Benigni');
INSERT INTO directors (director_id, name) VALUES (20, 'George Lucas');
INSERT INTO directors (director_id, name) VALUES (21, 'James Cameron');
INSERT INTO directors (director_id, name) VALUES (22, 'Hayao Miyazaki');
INSERT INTO directors (director_id, name) VALUES (23, 'Alfred Hitchcock');
INSERT INTO directors (director_id, name) VALUES (24, 'Roman Polanski');
INSERT INTO directors (director_id, name) VALUES (25, 'Luc Besson');
INSERT INTO directors (director_id, name) VALUES (26, 'Bong Joon Ho');
INSERT INTO directors (director_id, name) VALUES (27, 'Roger Allers, Rob Minkoff');
INSERT INTO directors (director_id, name) VALUES (28, 'Ridley Scott');
INSERT INTO directors (director_id, name) VALUES (29, 'Tony Kaye');
INSERT INTO directors (director_id, name) VALUES (30, 'Bryan Singer');
INSERT INTO directors (director_id, name) VALUES (31, 'Michael Curtiz');
INSERT INTO directors (director_id, name) VALUES (32, 'Damien Chazelle');
INSERT INTO directors (director_id, name) VALUES (33, 'Olivier Nakache, Ã‰ric Toledano');
INSERT INTO directors (director_id, name) VALUES (34, 'Charles Chaplin');
INSERT INTO directors (director_id, name) VALUES (35, 'Masaki Kobayashi');
INSERT INTO directors (director_id, name) VALUES (36, 'Isao Takahata');
INSERT INTO directors (director_id, name) VALUES (37, 'Giuseppe Tornatore');
INSERT INTO directors (director_id, name) VALUES (38, 'Andrew Stanton');
INSERT INTO directors (director_id, name) VALUES (39, 'Florian Henckel von Donnersmarck');
INSERT INTO directors (director_id, name) VALUES (40, 'Billy Wilder');
INSERT INTO directors (director_id, name) VALUES (41, 'Stanley Kubrick');
INSERT INTO directors (director_id, name) VALUES (42, 'Anthony Russo, Joe Russo');
INSERT INTO directors (director_id, name) VALUES (43, 'Sam Mendes');
INSERT INTO directors (director_id, name) VALUES (44, 'Bob Persichetti, Peter Ramsey, Rodney Rothman');     
INSERT INTO directors (director_id, name) VALUES (45, 'Todd Phillips');
INSERT INTO directors (director_id, name) VALUES (46, 'Park Chan-wook');
INSERT INTO directors (director_id, name) VALUES (47, 'Mel Gibson');
INSERT INTO directors (director_id, name) VALUES (48, 'John Lasseter');
INSERT INTO directors (director_id, name) VALUES (49, 'Lee Unkrich, Adrian Molina');
INSERT INTO directors (director_id, name) VALUES (50, 'Jon Watts');
INSERT INTO directors (director_id, name) VALUES (51, 'Wolfgang Petersen');
INSERT INTO directors (director_id, name) VALUES (52, 'Gus Van Sant');
INSERT INTO directors (director_id, name) VALUES (53, 'Lee Unkrich');
INSERT INTO directors (director_id, name) VALUES (54, 'Darren Aronofsky');
INSERT INTO directors (director_id, name) VALUES (55, 'Rajkumar Hirani');
INSERT INTO directors (director_id, name) VALUES (56, 'Makoto Shinkai');
INSERT INTO directors (director_id, name) VALUES (57, 'Stanley Donen, Gene Kelly');
INSERT INTO directors (director_id, name) VALUES (58, 'Richard Marquand');
INSERT INTO directors (director_id, name) VALUES (59, 'Michel Gondry');
INSERT INTO directors (director_id, name) VALUES (60, 'Orson Welles');
INSERT INTO directors (director_id, name) VALUES (61, 'David Lean');
INSERT INTO directors (director_id, name) VALUES (62, 'Nadine Labaki');
INSERT INTO directors (director_id, name) VALUES (63, 'Fritz Lang');
INSERT INTO directors (director_id, name) VALUES (64, 'Thomas Vinterberg');
INSERT INTO directors (director_id, name) VALUES (65, 'Jean-Pierre Jeunet');
INSERT INTO directors (director_id, name) VALUES (66, 'Brian De Palma');
INSERT INTO directors (director_id, name) VALUES (67, 'Elem Klimov');
INSERT INTO directors (director_id, name) VALUES (68, 'Robert Mulligan');
INSERT INTO directors (director_id, name) VALUES (69, 'George Roy Hill');
INSERT INTO directors (director_id, name) VALUES (70, 'Pete Docter, Bob Peterson');
INSERT INTO directors (director_id, name) VALUES (71, 'Curtis Hanson');
INSERT INTO directors (director_id, name) VALUES (72, 'Thomas Kail');
INSERT INTO directors (director_id, name) VALUES (73, 'Michael Mann');
INSERT INTO directors (director_id, name) VALUES (74, 'Guy Ritchie');
INSERT INTO directors (director_id, name) VALUES (75, 'John McTiernan');
INSERT INTO directors (director_id, name) VALUES (76, 'Asghar Farhadi');
INSERT INTO directors (director_id, name) VALUES (77, 'Vittorio De Sica');
INSERT INTO directors (director_id, name) VALUES (78, 'Denis Villeneuve');
INSERT INTO directors (director_id, name) VALUES (79, 'Aamir Khan, Amole Gupte');
INSERT INTO directors (director_id, name) VALUES (80, 'Nitesh Tiwari');
INSERT INTO directors (director_id, name) VALUES (81, 'Oliver Hirschbiegel');
INSERT INTO directors (director_id, name) VALUES (82, 'Matt Reeves');
INSERT INTO directors (director_id, name) VALUES (83, 'Florian Zeller');
INSERT INTO directors (director_id, name) VALUES (84, 'Joseph L. Mankiewicz');
INSERT INTO directors (director_id, name) VALUES (85, 'Peter Farrelly');
INSERT INTO directors (director_id, name) VALUES (86, 'Clint Eastwood');
INSERT INTO directors (director_id, name) VALUES (87, 'Stanley Kramer');
INSERT INTO directors (director_id, name) VALUES (88, 'Guillermo del Toro');
INSERT INTO directors (director_id, name) VALUES (89, 'Ron Howard');
INSERT INTO directors (director_id, name) VALUES (90, 'M. Night Shyamalan');
INSERT INTO directors (director_id, name) VALUES (91, 'Terry Gilliam, Terry Jones');
INSERT INTO directors (director_id, name) VALUES (92, 'Paul Thomas Anderson');
INSERT INTO directors (director_id, name) VALUES (93, 'Peter Weir');
INSERT INTO directors (director_id, name) VALUES (94, 'John Huston');
INSERT INTO directors (director_id, name) VALUES (95, 'John Sturges');
INSERT INTO directors (director_id, name) VALUES (96, 'Ethan Coen, Joel Coen');
INSERT INTO directors (director_id, name) VALUES (97, 'Andrew Stanton, Lee Unkrich');
INSERT INTO directors (director_id, name) VALUES (98, 'James McTeigue');
INSERT INTO directors (director_id, name) VALUES (99, 'David Lynch');
INSERT INTO directors (director_id, name) VALUES (100, 'Victor Fleming, George Cukor, Sam Wood');
INSERT INTO directors (director_id, name) VALUES (101, 'Pete Docter, Ronnie Del Carmen');
INSERT INTO directors (director_id, name) VALUES (102, 'John Carpenter');
INSERT INTO directors (director_id, name) VALUES (103, 'Juan JosÃ© Campanella');
INSERT INTO directors (director_id, name) VALUES (104, 'Danny Boyle');
INSERT INTO directors (director_id, name) VALUES (105, 'Martin McDonagh');
INSERT INTO directors (director_id, name) VALUES (106, 'Gavin O Connor');
INSERT INTO directors (director_id, name) VALUES (107, 'Joel Coen, Ethan Coen');
INSERT INTO directors (director_id, name) VALUES (108, 'Elia Kazan');
INSERT INTO directors (director_id, name) VALUES (109, 'Majid Majidi');
INSERT INTO directors (director_id, name) VALUES (110, 'David Yates');
INSERT INTO directors (director_id, name) VALUES (111, 'Carol Reed');
INSERT INTO directors (director_id, name) VALUES (112, 'Steve McQueen');
INSERT INTO directors (director_id, name) VALUES (113, 'William Wyler');
INSERT INTO directors (director_id, name) VALUES (114, 'Clyde Bruckman, Buster Keaton');
INSERT INTO directors (director_id, name) VALUES (115, 'Michael Cimino');
INSERT INTO directors (director_id, name) VALUES (116, 'Richard Linklater');
INSERT INTO directors (director_id, name) VALUES (117, 'Ingmar Bergman');
INSERT INTO directors (director_id, name) VALUES (118, 'Jim Sheridan');
INSERT INTO directors (director_id, name) VALUES (119, 'Wes Anderson');
INSERT INTO directors (director_id, name) VALUES (120, 'Lenny Abrahamson');
INSERT INTO directors (director_id, name) VALUES (121, 'Buster Keaton');
INSERT INTO directors (director_id, name) VALUES (122, 'Satyajit Ray');
INSERT INTO directors (director_id, name) VALUES (123, 'Dean DeBlois, Chris Sanders');
INSERT INTO directors (director_id, name) VALUES (124, 'Henri-Georges Clouzot');
INSERT INTO directors (director_id, name) VALUES (125, 'Sergio Pablos, Carlos MartÃ­nez LÃ³pez');
INSERT INTO directors (director_id, name) VALUES (126, 'George Miller');
INSERT INTO directors (director_id, name) VALUES (127, 'DamiÃ¡n Szifron');
INSERT INTO directors (director_id, name) VALUES (128, 'Pete Docter, David Silverman, Lee Unkrich');        
INSERT INTO directors (director_id, name) VALUES (129, 'Adam Elliot');
INSERT INTO directors (director_id, name) VALUES (130, 'Carl Theodor Dreyer');
INSERT INTO directors (director_id, name) VALUES (131, 'Terry George');
INSERT INTO directors (director_id, name) VALUES (132, 'John G. Avildsen');
INSERT INTO directors (director_id, name) VALUES (133, 'YasujirÃ´ Ozu');
INSERT INTO directors (director_id, name) VALUES (134, 'Oliver Stone');
INSERT INTO directors (director_id, name) VALUES (135, 'James Mangold');
INSERT INTO directors (director_id, name) VALUES (136, 'Rob Reiner');
INSERT INTO directors (director_id, name) VALUES (137, 'Sean Penn');
INSERT INTO directors (director_id, name) VALUES (138, 'Victor Fleming, George Cukor, Mervyn LeRoy');       
INSERT INTO directors (director_id, name) VALUES (139, 'Tom McCarthy');
INSERT INTO directors (director_id, name) VALUES (140, 'Harold Ramis');
INSERT INTO directors (director_id, name) VALUES (141, 'Brad Bird, Jan Pinkava');
INSERT INTO directors (director_id, name) VALUES (142, 'William Friedkin');
INSERT INTO directors (director_id, name) VALUES (143, 'Lasse HallstrÃ¶m');
INSERT INTO directors (director_id, name) VALUES (144, 'Brad Bird');
INSERT INTO directors (director_id, name) VALUES (145, 'Cagan Irmak');
INSERT INTO directors (director_id, name) VALUES (146, 'Stuart Rosenberg');
INSERT INTO directors (director_id, name) VALUES (147, 'John Ford');
INSERT INTO directors (director_id, name) VALUES (148, 'Gillo Pontecorvo');
INSERT INTO directors (director_id, name) VALUES (149, 'Gore Verbinski');
INSERT INTO directors (director_id, name) VALUES (150, 'Ernst Lubitsch');
INSERT INTO directors (director_id, name) VALUES (151, 'Alejandro G. IÃ±Ã¡rritu');
INSERT INTO directors (director_id, name) VALUES (152, 'Robert Wise');
INSERT INTO directors (director_id, name) VALUES (153, 'Terry Jones');
INSERT INTO directors (director_id, name) VALUES (154, 'FranÃ§ois Truffaut');
INSERT INTO directors (director_id, name) VALUES (155, 'Mathieu Kassovitz');
INSERT INTO directors (director_id, name) VALUES (156, 'Ron Clements, John Musker');
INSERT INTO directors (director_id, name) VALUES (157, 'Gary Trousdale, Kirk Wise');
INSERT INTO directors (director_id, name) VALUES (158, 'Richard Attenborough');
INSERT INTO directors (director_id, name) VALUES (159, 'Tate Taylor');
INSERT INTO directors (director_id, name) VALUES (160, 'Kevin Costner');